### ISSUE TITLE
405 Method not Allowed CORS Response

### ISSUE THREAD

**Issue by AL3X1** [tusdotnet/tusdotnet#92]
Hello everyone! 
I have stuck with CORS issue using ASP.NET Core 3 and kubernetes.
I have enabled CORS at all.

Here is my Startup.Configure method
        

           app.UseHttpsRedirection();

            app.UseRouting();

            app.UseCors(builder => builder
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowAnyOrigin()
                .WithExposedHeaders(CorsHelper.GetExposedHeaders()));

            app.UseAuthorization();

            app.UseEndpoints(endpoints => { endpoints.MapControllers(); });

            var s3Client = new BlobClient(config.AzureBlobConnectionString);
            var attachementRepo = new AttachmentRepository(config.ConnectionString);
            var attachmentService = new AttachmentService(s3Client, attachementRepo);
            
            //TODO: move to config
            var projectRootPath = env.ContentRootPath;
            var tusStoragePath = Path.Join(projectRootPath, "tusfiles");
            if (!Directory.Exists(tusStoragePath))
            {
                Directory.CreateDirectory(tusStoragePath);
            }
            
            var store = new TusDiskStore(tusStoragePath, true);

            app.UseTus(httpContext => new DefaultTusConfiguration
            {
                Store = store,
                // On what url should we listen for uploads?
                UrlPath = "/files",
                Events = new Events
                {
                    OnFileCompleteAsync = async eventContext =>
                    {
                        var file = await eventContext.GetFileAsync();

                        var meta = await file.GetMetadataAsync(CancellationToken.None);
                        var att = meta["attachmentId"];
                        var attVal = att.GetString(Encoding.Default);
                        var attachmentId = Guid.Parse(attVal);

                        var fileStream = await file.GetContentAsync(CancellationToken.None);

                        attachmentService.AppendFileFile(attachmentId, fileStream);

                        await store.DeleteFileAsync(file.Id, CancellationToken.None);
                        
                        Console.WriteLine($"OnFileComplete {file.Id} attachment:{attVal}");
                    },
                }
            });

Also i've added `services.AddCors();` to ConfigureServices.

When i'm trying to perform request from iOS Application, TUS JS Client or TUS DotNet client I receiving

`405 Method not allowed` error

Here is logs in Chrome console:

`Access to XMLHttpRequest at 'https:/domain/files/5189f5fbd1c34ce6bf83e137d14546e9' from origin 'http://localhost:63343' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
upload.js:593 PATCH https:/domain/files/5189f5fbd1c34ce6bf83e137d14146e9 net::ERR_FAILED`

and response

`The remote server returned an error: (405) Method Not Allowed.
URL:https://domain/files
MethodNotAllowed:Method Not Allowed
405 Method Not Allowed`

from TUSClient.

I've tried also enable CORS on Kubernetes level (in ingress), but receiving the same.

Where I wrong?

UPD: Also, when i'm trying to use proxy as temporary solution to update my files from server, i receiving

`System.Exception: Offset Header Missing`

**Comment by AL3X1** [comment]
Problem was on nginx Ingress configuration.
My default endpoint was started from `/api/`, e.g. i had these settings in my yaml profile.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-api
  namespace: my-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($request_uri ~ ^(/files/(.*)$)) {
          return 301 /api$1;
      }
spec:
  rules:
    - host: domain.com
      http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: web-api
              servicePort: 80
```

TUS was bound on `/files/` endpoint, so i have requests to not existing `/files/` endpoint instead `/api/files`. I've just added redirecting all /files/ requests to /api/files and it works.
